org.gradle.jvmargs=-Xmx2g -Xms512m
org.gradle.caching=true
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.paths=/Library/Java/JavaVirtualMachines/zulu-25.jdk/Contents/Home
java.languageVersion=25
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.vfs.watch=true
