---
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    fields:
      type: microservice-log
    fields_under_root: true

processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 10
      target: ""
      overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]
# end-of-file
