name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  versions:
    uses: ./.github/workflows/central-versions.yml

  build:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${{ needs.versions.outputs.actions_checkout_version }}
      - name: Set up JDK 25
        uses: actions/setup-java@${{ needs.versions.outputs.actions_setup_java_version }}
        with:
          distribution: temurin
          java-version: '25'
      - name: Cache Gradle
        uses: actions/cache@${{ needs.versions.outputs.actions_cache_version }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle/deps.versions.toml') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Gradle version check
        run: ./gradlew --configuration-cache versionCheck
      - name: Schema compatibility
        run: ./gradlew --configuration-cache schemaCompatibilityCheck
      - name: Build & Test
        run: ./gradlew --configuration-cache check

  docs:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${{ needs.versions.outputs.actions_checkout_version }}
      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@${{ needs.versions.outputs.davidanson_markdownlint_cli2_action_version }}